services:
  ui:
    build: ../../wallet-fe
    depends_on:
      - api
    ports:
      - 8000:80

  api:
    build: ../../wallet-be
    environment:
      # Note: in the hostname, we must use the name of the database container (so its "db" instead of typical "locahost")
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_LOGGING_LEVEL_ROOT: INFO
      SPRING_SERVER_PORT: 8080
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
