version: '3.3'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
